baseURL = "http://example.org/"
languageCode = "en-us"
title = "SusAI"
subtitle="Sustainable development of artificial Inteligence"

[taxonomies]
    category = 'categories'
    tag = 'tags'
    author = 'authors'